### ISSUE TITLE
adding some auditory feedback

### ISSUE THREAD

**Issue by peevees** [tollyx/TextAdv#1]
as _the game_ seem heavenly dependent on **console ouput**, you could make use of the pc speaker for audio using: `Console.Beep();`
more info can be found at:
[link to msdn about Console.Beep()](https://msdn.microsoft.com/en-us/library/8hftfeyw(v=vs.110).aspx)
[link to msdn about Console.Beep(Int32, Int32)](https://msdn.microsoft.com/en-us/library/4fe3hdb1(v=vs.110).aspx)
or if you want to complicate it you could try: `Console.WriteLine("\a");` 🤔  
it creates a beep too but seems kind of complicated to control duration and hertz of the beep.

**Comment by tollyx** [comment]
Yeah, I'll definitely want to add some sound at some point. And as cool it would be to stay minimal and just use `Console.Beep()`, I see two potential issues: 

1. It's synchronous, so I would not want to play anything longer than a few ms with it.
2. It's very limited in what sounds it can create. But this might be a positive if I want it to feel retro.

I will probably play around with it and look at some other solutions before deciding what I want.

**Comment by peevees** [comment]
Sounds Awesome (pun intended) 😆
